name: Deploy to Azure Container Registry

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@main
        with:
          fetch-depth: 0

      - name: "Setup DotNet 8 Environment"
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.0

      - run: |
          docker build -t ${{ secrets.ACR_NAME }}/hcportal-be-image:latest .
          mkdir ./docker_image
          docker save hcportal-be-image:latest | gzip > ./docker_image/hcportal-be-image.tar.gz

      - name: "Commit files"
        run: |
          git config --local user.email "g.maressolano090@mybvc.ca"
          git config --local user.name "github-actions[bot]"
          git add ./docker_image
          git commit -a -m "Update backend docker image"

      - name: Push Docker image to Git infra repo
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.HCPORTAL_INFRA_REPO_PUSH_KEY }}
          repository: Health-Care-BVC-project/h-c-infra
          force: true
          directory: ./docker_image
          branch: main
